language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm i -g npm@5.7.1 # delete once 5.7.X is out of "pre-release"
  - npm ci             # faster, goes only from package-lock
before_script:
  - psql -c 'create database "boilermaker-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
   - npm run build-client # make the bundle
   - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: badgrey # see README
  api_key:
    secure: "OREtcYWHgTm+uZPylBM1mr4bKCylnL+F+FLLO8meJYfzTASY5dstWkqlSuqMI+HpE0aJX7vgebVaGPLDLyA/aJ28wDO9Y8CewRRe/Og5e5MB/ff3OEl351+0Y1uinv6RPHn8XCENUugyz/zhIjKmGXIJ34O7he1m8IaG1Uy2gpnQ3ymNUcqlW95QX+2x3ybt8UZouAUzQUpeAcHVb3n2/Oi/EQcf4hZxlzjJnRXUplE81gd3Hz1zparUkhJehViUnecuNF0T459rJ6vNZju0U2CTjB9jRfH0YCFPeUlNX8OkBidUfk+Qa4H0t9S1fnMF4iLvp1lCM9AQWJKyqrsomMRrgugWj6xL4dxxC2U3k+rqoRg2ZuSLWvc7wIsr3Hw81CrqSg3a3Pge6cU0xIR9FsxrcOW1GOIrRarerX8N/DQVyzYxtsMB4jp64+MILPv2crSy799bEHKfLL+jfLyPIuAVj5b/UJlhfMN2sgCUGwZ3RquJO+fOO9qrASqHl1bsSREn6bJji4FcRrLIczI8WpPJlkOUhX7+o619pqXLLJBB6nPzKK/OpkWzcfIEhMfe7i4Sd4BPFPsOO/CPMZMJLXgpLAlPWukH82lU1h9+G/KYywmfVLl2h8+FfoHxq1eTRPbPMtcU2qB98v7plOIvQYK/WCLyMC5cCwQdNOYpTvY=" # see README
